### ISSUE TITLE
Simply does not work for me

### ISSUE THREAD

**Issue by chrisfair** [casonadams/alacritty-shell#5]
I installed yq and I followed the instructions for installing with ohmyzsh and when I had finished it did not provide the option to switch colorschemes with a command.

**Comment by casonadams** [comment]
@chrisfair can you please share your configuration with me to better help?

What does you .zshrc file look like?
What does your alacritty.yml file look like?

**Comment by casonadams** [comment]
Also note if you don't have themes in your alacrity file you need to use the `add` command or manually and then before the theme switcher will work.

Maybe this isn't too clear in the README?

**Comment by casonadams** [comment]
@chrisfair here is an example (if you ran `add_alacritty_nord`)

You should then see this configuration in your `alacritty.yml` file.

```yml
schemes:
  nord: &nord
    transparent_background_colors: true
    primary:
      background: "0x2e3440"
      foreground: "0xe5e9f0"
    normal:
      black: "0x3b4252"
      red: "0xbf616a"
      green: "0xa3be8c"
      yellow: "0xebcb8b"
      blue: "0x81a1c1"
      magenta: "0xb48ead"
      cyan: "0x88c0d0"
      white: "0xd3d5bd"
    bright:
      black: "0x757a85"
      red: "0xbf616a"
      green: "0xa3be8c"
      yellow: "0xebcb8b"
      blue: "0x81a1c1"
      magenta: "0xb48ead"
      cyan: "0x88c0d0"
      white: "0xeceff4"
    indexed_colors:
      - {index: 208, color: "0xd08770"}
colors: *nord
```
